### ISSUE TITLE
Code duplicated in format.php file

### ISSUE THREAD

**Issue by francescvalenzuela** [michael2to3/moodle-qformat_excel#1]
Class is duplicated. See:

https://github.com/michael2to3/moodle-qformat_excel/blob/de17f9412581331fb88a72d9592282096b0f2be1/format.php#L299

**Comment by francescvalenzuela** [comment]
I've just seen that this happens in all php files

**Comment by michael2to3** [comment]
bro, just send new pr. Do you want better style? Just do it. Don't waste my time

**Comment by francescvalenzuela** [comment]
First of all thank you for sharing your code and sorry for the length of this message. 

I'm sorry if I bothered you by opening the issue. I followed the instructions in your readme. I just wanted to help. I don't see how to create a branch to make the change. Probably the repository configuration does not allow it to my user. 

I opened the issue not because there is a style error but because the content of the file is completely duplicated, all the code is twice, and it is not the only file. 

I suggest you check it before replying again to avoid misunderstandings. However, you are free to change or not this code, it is a simple suggestion. I am not asking you for anything. You can delete the issue and forget all this if this represents a problem for you. 

I'm available if you need further information. Take care.

**Comment by michael2to3** [comment]
Hmm, that's right. This was not done by me, but by a script to bypass code authentication. I must have made a mistake somewhere. Since I have already passed the subject at the university, I will return the changes to the code obfuscation. This way the old code will work fine. In the future, if you want to make a pr, then make a fork, create a branch and make changes there, after which github will offer you to create a pr for this repository. Thank you for explaining your issue in more detail
